"""Add user_created_time column

Revision ID: 9ea38bd9ef15
Revises: 4691f0d01541
Create Date: 2026-02-05 19:32:49.480299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea38bd9ef15'
down_revision: Union[str, Sequence[str], None] = '4691f0d01541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_created_time')
    # ### end Alembic commands ###
